name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile and test
        run: |
          # Compile Java files from src/test directory
          javac -cp .:lib/* -d out src/test/*.java
          # Run tests
          java -cp .:lib/*:out org.junit.runner.JUnitCore test.ServerTest