name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and test
        run: |
          javac -cp .:lib/* -d out src/*.java
          java -cp .:lib/*:out org.junit.runner.JUnitCore test.ServerTest
